//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagmentService.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectResource
    {
        public int IdProjectResource { get; set; }
        public int IdProject { get; set; }
        public byte IdResource { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
