//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagmentService.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InfoProjectTask
    {
        public string Title { get; set; }
        public string ResponsiblePerson { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string Task { get; set; }
        public string StageTitle { get; set; }
        public string Skill { get; set; }
        public string IsClose { get; set; }
    }
}
